# the conda packages that you need installed in your environment.
channels:
  - conda-forge
  - pytorch

dependencies:
  - jupyter_contrib_nbextensions==0.5.1
  - jupyterhub-singleuser==2.3.1 # Explicitly add jupyterhub-singleuser so the base url setup works
  - python==3.8.10
  - numpy
  - matplotlib
  - ipympl
  - pandas
  - scikit-learn
  - nbgitpuller
  - jupyterlab-git
  - pykdtree
  - pyembree
  - scikit-build
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.6
  - cudnn
  - pip:
      - nbdime
      - jupyterhub-roothooks==0.2.1
      - allensdk==2.13.6
      - caveclient==4.16.2
      - nglui==2.10.1
      - meshparty==1.16.5
      - pcg-skel==0.3.0
      - git+https://github.com/AllenInstitute/em_coregistration.git@swdb
      - git+https://github.com/cajal/microns_phase3_nda.git
      - git+https://github.com/AllenInstitute/brain_observatory_utilities.git@v0.1.2
variables:
  DJ_HOST: swdb.crjvviai1xxh.us-west-2.rds.amazonaws.com
  DJ_USER: dbuser
  DJ_PASS: <fy[B)2z[ksS%eeSOaghO}>_:z}Le&>NnpYz5ObWW
