# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge

dependencies:
  - jupyter_contrib_nbextensions #==0.5.1
  - python
  - numpy
  - matplotlib
  - pandas
  - scikit-learn
  - nbgitpuller
  - jupyterlab-git 
  # Add other packages here
  # -
  #
