# the conda packages that you need installed in your environment.
channels:
  - conda-forge

dependencies:
  - jupyter_contrib_nbextensions==0.5.1
  - jupyterhub-singleuser==2.3.1 # Explicitly add jupyterhub-singleuser so the base url setup works
  - python==3.7.13
  - numpy
  - matplotlib
  - ipympl
  - pandas
  - scikit-learn
  - nbgitpuller
  - jupyterlab-git
  - pykdtree
  - pyembree
  - scikit-build
  - pip
  - pip:
      - jupyterhub-roothooks==0.2.1
      - allensdk==2.13.6
      - caveclient==4.16.1
      - nglui==2.10.0
      - meshparty==1.16.4
      - git+https://github.com/AllenInstitute/em_coregistration.git@swdb
      - git+https://github.com/cajal/microns_phase3_nda.git
