# This is the standard conda configuration file. Use this file to list
# the conda packages that you need installed in your environment.
channels:
  - conda-forge

dependencies:
  - jupyter_contrib_nbextensions==0.5.1
  - jupyterhub-singleuser==2.3.1 # Explicitly add jupyterhub-singleuser so the base url setup works
  # Add other packages here
  # -
